// Code generated by ndpgen. DO NOT EDIT.
//
// This file contains export wrappers for the Podcast capability.
// It is intended for use in Navidrome plugins built with extism-pdk.

use serde::{Deserialize, Serialize};

// Helper functions for skip_serializing_if with numeric types
#[allow(dead_code)]
fn is_zero_i32(value: &i32) -> bool { *value == 0 }
#[allow(dead_code)]
fn is_zero_u32(value: &u32) -> bool { *value == 0 }
#[allow(dead_code)]
fn is_zero_i64(value: &i64) -> bool { *value == 0 }
#[allow(dead_code)]
fn is_zero_u64(value: &u64) -> bool { *value == 0 }
#[allow(dead_code)]
fn is_zero_f32(value: &f32) -> bool { *value == 0.0 }
#[allow(dead_code)]
fn is_zero_f64(value: &f64) -> bool { *value == 0.0 }


/// PodcastStatus is the status of a podcast channel or episode.
/// One of: "new", "downloading", "completed", "error", "deleted", "skipped".
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum PodcastStatus {
    New,
    Downloading,
    Completed,
    #[default]
    Error,
    Deleted,
    Skipped,
}


/// PodcastChannel represents the PodcastChannel data structure.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PodcastChannel {
    /// ID is the channel ID.
    #[serde(default)]
    pub id: String,
    /// URL is the podcast channel feed URL.
    #[serde(default)]
    pub url: String,
    /// Title is the channel title.
    #[serde(default)]
    pub title: Option<String>,
    /// Description is the channel description.
    #[serde(default)]
    pub description: Option<String>,
    /// CoverArt is an ID used for retrieving cover art.
    #[serde(default)]
    pub cover_art: Option<String>,
    /// OriginalImageUrl is the URL of the original channel image.
    #[serde(default)]
    pub original_image_url: Option<String>,
    /// Status is the channel status.
    #[serde(default)]
    pub status: PodcastStatus,
    /// ErrorMessage is an error message, if status is \"error\".
    #[serde(default)]
    pub error_message: Option<String>,
    /// Episodes are the podcast episodes for this channel.
    #[serde(default)]
    pub episodes: Vec<PodcastEpisode>,
}

/// PodcastEpisode represents the PodcastEpisode data structure.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PodcastEpisode {
    /// ID is the episode ID.
    #[serde(default)]
    pub id: String,
    /// StreamID is the ID used for streaming the episode.
    #[serde(default)]
    pub stream_id: Option<String>,
    /// ChannelID is the ID of the podcast channel this episode belongs to.
    #[serde(default)]
    pub channel_id: String,
    /// Title is the episode title.
    #[serde(default)]
    pub title: Option<String>,
    /// Description is the episode description.
    #[serde(default)]
    pub description: Option<String>,
    /// PublishDate is the publication date as an ISO 8601 string.
    #[serde(default)]
    pub publish_date: Option<String>,
    /// Status is the episode status.
    #[serde(default)]
    pub status: PodcastStatus,
    /// ErrorMessage is an error message, if status is \"error\".
    #[serde(default)]
    pub error_message: Option<String>,
    /// StreamURL is the URL to stream the episode from (when not downloaded).
    #[serde(default)]
    pub stream_url: Option<String>,
    /// CoverArt is an ID used for retrieving cover art.
    #[serde(default)]
    pub cover_art: Option<String>,
    /// Year is the publication year.
    #[serde(default)]
    pub year: Option<i32>,
    /// Genre is the genre (commonly \"Podcast\").
    #[serde(default)]
    pub genre: Option<String>,
    /// Duration is the episode duration in seconds.
    #[serde(default)]
    pub duration: Option<i32>,
    /// BitRate is the episode bit rate in kbps.
    #[serde(default)]
    pub bit_rate: Option<i32>,
    /// Size is the episode size in bytes.
    #[serde(default)]
    pub size: Option<i64>,
    /// ContentType is the MIME content type of the episode.
    #[serde(default)]
    pub content_type: Option<String>,
    /// Suffix is the file suffix (e.g. \"mp3\").
    #[serde(default)]
    pub suffix: Option<String>,
    /// Path is the relative path of the downloaded file, if available.
    #[serde(default)]
    pub path: Option<String>,
}

/// GetPodcastChannelsRequest represents the GetPodcastChannelsRequest data structure.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetPodcastChannelsRequest {
    /// IncludeEpisodes controls whether episodes are returned with each channel.
    #[serde(default)]
    pub include_episodes: bool,
}

/// GetPodcastChannelsResponse represents the GetPodcastChannelsResponse data structure.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetPodcastChannelsResponse {
    /// Channels is the list of podcast channels.
    #[serde(default)]
    pub channels: Vec<PodcastChannel>,
}

/// GetPodcastChannelRequest represents the GetPodcastChannelRequest data structure.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetPodcastChannelRequest {
    /// ID is the channel ID.
    #[serde(default)]
    pub id: String,
    /// IncludeEpisodes controls whether episodes are returned with the channel.
    #[serde(default)]
    pub include_episodes: bool,
}

/// GetPodcastChannelResponse represents the GetPodcastChannelResponse data structure.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetPodcastChannelResponse {
    /// Channel is the requested podcast channel.
    #[serde(default)]
    pub channel: PodcastChannel,
}

/// GetNewestEpisodesRequest represents the GetNewestEpisodesRequest data structure.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetNewestEpisodesRequest {
    /// Count is the maximum number of episodes to return.
    #[serde(default)]
    pub count: i32,
}

/// GetNewestEpisodesResponse represents the GetNewestEpisodesResponse data structure.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetNewestEpisodesResponse {
    /// Episodes is the list of most recently published episodes.
    #[serde(default)]
    pub episodes: Vec<PodcastEpisode>,
}

/// CreatePodcastChannelRequest represents the CreatePodcastChannelRequest data structure.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreatePodcastChannelRequest {
    /// URL is the feed URL of the podcast to subscribe to.
    #[serde(default)]
    pub url: String,
}

/// CreatePodcastChannelResponse represents the CreatePodcastChannelResponse data structure.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreatePodcastChannelResponse {
    /// Channel is the newly created podcast channel, if created synchronously.
    #[serde(default)]
    pub channel: Option<PodcastChannel>,
}

/// RefreshPodcastsRequest represents the RefreshPodcastsRequest data structure.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RefreshPodcastsRequest {
    /// ChannelIDs is the list of channel IDs to refresh. When empty, all channels are refreshed.
    #[serde(default)]
    pub channel_ids: Vec<String>,
}

/// RefreshPodcastsResponse represents the RefreshPodcastsResponse data structure.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RefreshPodcastsResponse {
    /// Refreshed is the list of channel IDs that were refreshed.
    #[serde(default)]
    pub refreshed: Vec<String>,
}

/// DownloadPodcastEpisodeRequest represents the DownloadPodcastEpisodeRequest data structure.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DownloadPodcastEpisodeRequest {
    /// ID is the podcast episode ID to download.
    #[serde(default)]
    pub id: String,
}

/// DownloadPodcastEpisodeResponse represents the DownloadPodcastEpisodeResponse data structure.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DownloadPodcastEpisodeResponse {
    /// Episode is the updated episode, with its new status, if available.
    #[serde(default)]
    pub episode: Option<PodcastEpisode>,
}

/// DeletePodcastChannelRequest represents the DeletePodcastChannelRequest data structure.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeletePodcastChannelRequest {
    /// ID is the channel ID to delete.
    #[serde(default)]
    pub id: String,
}

/// DeletePodcastChannelResponse represents the DeletePodcastChannelResponse data structure.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeletePodcastChannelResponse {
    /// Deleted is true when the channel was deleted.
    #[serde(default)]
    pub deleted: bool,
}

/// DeletePodcastEpisodeRequest represents the DeletePodcastEpisodeRequest data structure.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeletePodcastEpisodeRequest {
    /// ID is the episode ID to delete.
    #[serde(default)]
    pub id: String,
}

/// DeletePodcastEpisodeResponse represents the DeletePodcastEpisodeResponse data structure.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeletePodcastEpisodeResponse {
    /// Deleted is true when the episode was deleted.
    #[serde(default)]
    pub deleted: bool,
}

/// Error represents an error from a capability method.
#[derive(Debug)]
pub struct Error {
    pub message: String,
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl std::error::Error for Error {}

impl Error {
    pub fn new(message: impl Into<String>) -> Self {
        Self { message: message.into() }
    }
}


/// GetChannelsProvider provides the GetChannels function.
pub trait GetChannelsProvider {
    fn get_channels(&self, req: GetPodcastChannelsRequest) -> Result<GetPodcastChannelsResponse, Error>;
}

/// GetChannelProvider provides the GetChannel function.
pub trait GetChannelProvider {
    fn get_channel(&self, req: GetPodcastChannelRequest) -> Result<GetPodcastChannelResponse, Error>;
}

/// GetNewestEpisodesProvider provides the GetNewestEpisodes function.
pub trait GetNewestEpisodesProvider {
    fn get_newest_episodes(&self, req: GetNewestEpisodesRequest) -> Result<GetNewestEpisodesResponse, Error>;
}

/// CreateChannelProvider provides the CreateChannel function.
pub trait CreateChannelProvider {
    fn create_channel(&self, req: CreatePodcastChannelRequest) -> Result<CreatePodcastChannelResponse, Error>;
}

/// RefreshChannelsProvider provides the RefreshChannels function.
pub trait RefreshChannelsProvider {
    fn refresh_channels(&self, req: RefreshPodcastsRequest) -> Result<RefreshPodcastsResponse, Error>;
}

/// DownloadEpisodeProvider provides the DownloadEpisode function.
pub trait DownloadEpisodeProvider {
    fn download_episode(&self, req: DownloadPodcastEpisodeRequest) -> Result<DownloadPodcastEpisodeResponse, Error>;
}

/// DeleteChannelProvider provides the DeleteChannel function.
pub trait DeleteChannelProvider {
    fn delete_channel(&self, req: DeletePodcastChannelRequest) -> Result<DeletePodcastChannelResponse, Error>;
}

/// DeleteEpisodeProvider provides the DeleteEpisode function.
pub trait DeleteEpisodeProvider {
    fn delete_episode(&self, req: DeletePodcastEpisodeRequest) -> Result<DeletePodcastEpisodeResponse, Error>;
}

/// Register the nd_podcast_get_channels export.
/// This macro generates the WASM export function for this method.
#[macro_export]
macro_rules! register_podcast_get_channels {
    ($plugin_type:ty) => {
        #[extism_pdk::plugin_fn]
        pub fn nd_podcast_get_channels(
            req: extism_pdk::Json<$crate::podcast::GetPodcastChannelsRequest>
        ) -> extism_pdk::FnResult<extism_pdk::Json<$crate::podcast::GetPodcastChannelsResponse>> {
            let plugin = <$plugin_type>::default();
            let result = $crate::podcast::GetChannelsProvider::get_channels(&plugin, req.into_inner())?;
            Ok(extism_pdk::Json(result))
        }
    };
}

/// Register the nd_podcast_get_channel export.
/// This macro generates the WASM export function for this method.
#[macro_export]
macro_rules! register_podcast_get_channel {
    ($plugin_type:ty) => {
        #[extism_pdk::plugin_fn]
        pub fn nd_podcast_get_channel(
            req: extism_pdk::Json<$crate::podcast::GetPodcastChannelRequest>
        ) -> extism_pdk::FnResult<extism_pdk::Json<$crate::podcast::GetPodcastChannelResponse>> {
            let plugin = <$plugin_type>::default();
            let result = $crate::podcast::GetChannelProvider::get_channel(&plugin, req.into_inner())?;
            Ok(extism_pdk::Json(result))
        }
    };
}

/// Register the nd_podcast_get_newest_episodes export.
/// This macro generates the WASM export function for this method.
#[macro_export]
macro_rules! register_podcast_get_newest_episodes {
    ($plugin_type:ty) => {
        #[extism_pdk::plugin_fn]
        pub fn nd_podcast_get_newest_episodes(
            req: extism_pdk::Json<$crate::podcast::GetNewestEpisodesRequest>
        ) -> extism_pdk::FnResult<extism_pdk::Json<$crate::podcast::GetNewestEpisodesResponse>> {
            let plugin = <$plugin_type>::default();
            let result = $crate::podcast::GetNewestEpisodesProvider::get_newest_episodes(&plugin, req.into_inner())?;
            Ok(extism_pdk::Json(result))
        }
    };
}

/// Register the nd_podcast_create_channel export.
/// This macro generates the WASM export function for this method.
#[macro_export]
macro_rules! register_podcast_create_channel {
    ($plugin_type:ty) => {
        #[extism_pdk::plugin_fn]
        pub fn nd_podcast_create_channel(
            req: extism_pdk::Json<$crate::podcast::CreatePodcastChannelRequest>
        ) -> extism_pdk::FnResult<extism_pdk::Json<$crate::podcast::CreatePodcastChannelResponse>> {
            let plugin = <$plugin_type>::default();
            let result = $crate::podcast::CreateChannelProvider::create_channel(&plugin, req.into_inner())?;
            Ok(extism_pdk::Json(result))
        }
    };
}

/// Register the nd_podcast_refresh_channels export.
/// This macro generates the WASM export function for this method.
#[macro_export]
macro_rules! register_podcast_refresh_channels {
    ($plugin_type:ty) => {
        #[extism_pdk::plugin_fn]
        pub fn nd_podcast_refresh_channels(
            req: extism_pdk::Json<$crate::podcast::RefreshPodcastsRequest>
        ) -> extism_pdk::FnResult<extism_pdk::Json<$crate::podcast::RefreshPodcastsResponse>> {
            let plugin = <$plugin_type>::default();
            let result = $crate::podcast::RefreshChannelsProvider::refresh_channels(&plugin, req.into_inner())?;
            Ok(extism_pdk::Json(result))
        }
    };
}

/// Register the nd_podcast_download_episode export.
/// This macro generates the WASM export function for this method.
#[macro_export]
macro_rules! register_podcast_download_episode {
    ($plugin_type:ty) => {
        #[extism_pdk::plugin_fn]
        pub fn nd_podcast_download_episode(
            req: extism_pdk::Json<$crate::podcast::DownloadPodcastEpisodeRequest>
        ) -> extism_pdk::FnResult<extism_pdk::Json<$crate::podcast::DownloadPodcastEpisodeResponse>> {
            let plugin = <$plugin_type>::default();
            let result = $crate::podcast::DownloadEpisodeProvider::download_episode(&plugin, req.into_inner())?;
            Ok(extism_pdk::Json(result))
        }
    };
}

/// Register the nd_podcast_delete_channel export.
/// This macro generates the WASM export function for this method.
#[macro_export]
macro_rules! register_podcast_delete_channel {
    ($plugin_type:ty) => {
        #[extism_pdk::plugin_fn]
        pub fn nd_podcast_delete_channel(
            req: extism_pdk::Json<$crate::podcast::DeletePodcastChannelRequest>
        ) -> extism_pdk::FnResult<extism_pdk::Json<$crate::podcast::DeletePodcastChannelResponse>> {
            let plugin = <$plugin_type>::default();
            let result = $crate::podcast::DeleteChannelProvider::delete_channel(&plugin, req.into_inner())?;
            Ok(extism_pdk::Json(result))
        }
    };
}

/// Register the nd_podcast_delete_episode export.
/// This macro generates the WASM export function for this method.
#[macro_export]
macro_rules! register_podcast_delete_episode {
    ($plugin_type:ty) => {
        #[extism_pdk::plugin_fn]
        pub fn nd_podcast_delete_episode(
            req: extism_pdk::Json<$crate::podcast::DeletePodcastEpisodeRequest>
        ) -> extism_pdk::FnResult<extism_pdk::Json<$crate::podcast::DeletePodcastEpisodeResponse>> {
            let plugin = <$plugin_type>::default();
            let result = $crate::podcast::DeleteEpisodeProvider::delete_episode(&plugin, req.into_inner())?;
            Ok(extism_pdk::Json(result))
        }
    };
}
